import { TrainerPayload } from '../types/trainer.types';

export const defaultTrainerValues: TrainerPayload = {
  userId: 0,
  tenantId: 0,
  trainerCode: '',
  displayName: '',
  profileImage: '',
  bio: '',
  experienceYears: 0,
  gender: '',
  dateOfBirth: '',
  phone: '',
  email: '',
  address: '',
  languagesKnown: [],
  specializations: [],
  certifications: [],
  employment: {
    employmentType: '',
    joiningDate: '',
    contractStartDate: '',
    contractEndDate: '',
    designation: '',
    department: '',
    status: '',
  },
  salary: {
    salaryType: '',
    paymentCycle: '',
    currency: '',
    basicSalary: 0,
    hourlyRate: 0,
    perSessionRate: 0,
    perClientRate: 0,
    perClassRate: 0,
    commissionType: '',
    commissionValue: 0,
    commissionBasedOn: '',
    minimumGuaranteedAmount: 0,
    overtimeApplicable: false,
    overtimeHourlyRate: 0,
  },
  allowances: [],
  deductions: [],
  paymentDetails: {
    paymentMode: '',
    bankName: '',
    accountHolderName: '',
    accountNumber: '',
    ifscCode: '',
    upiId: '',
    taxNumber: '',
  },
  availability: [
    { day: 'Monday', startTime: '', endTime: '', isAvailable: false },
    { day: 'Tuesday', startTime: '', endTime: '', isAvailable: false },
    { day: 'Wednesday', startTime: '', endTime: '', isAvailable: false },
    { day: 'Thursday', startTime: '', endTime: '', isAvailable: false },
    { day: 'Friday', startTime: '', endTime: '', isAvailable: false },
    { day: 'Saturday', startTime: '', endTime: '', isAvailable: false },
    { day: 'Sunday', startTime: '', endTime: '', isAvailable: false },
  ],
  bookingSettings: {
    canTakePersonalTraining: false,
    canTakeGroupClasses: false,
    canTakeOnlineSessions: false,
    canTakeTrialSessions: false,
    maxClients: 0,
    maxDailySessions: 0,
    maxWeeklySessions: 0,
    sessionDurationMinutes: 0,
    bufferTimeMinutes: 0,
    requiresApprovalForBooking: false,
  },
  commissionSettings: {
    eligibleForMembershipCommission: false,
    eligibleForPersonalTrainingCommission: false,
    eligibleForSupplementCommission: false,
    membershipCommissionPercentage: 0,
    ptCommissionPercentage: 0,
    supplementCommissionPercentage: 0,
  },
  attendanceSettings: {
    attendanceRequired: false,
    lateMarkAfterMinutes: 0,
    halfDayAfterMinutes: 0,
    minimumWorkingHours: 0,
    weeklyOffDays: [],
  },
  documents: [],
  emergencyContact: { name: '', relation: '', phone: '', address: '' },
  socialLinks: { instagram: '', facebook: '', youtube: '', website: '' },
  notes: '',
};
